export const enum Types{
    ADD_TO_TODO_LIST="ADD_TO_TODO_LIST",
    START_TODO="START_TODO",
    DELETE_TODO="DELETE_TODO",
    UPDATE_SETTINGS="UPDATE_SETTINGS",
    UPDATE_CURRENT_TODO="UPDATE_CURRENT_TODO",
    CHANGE_CURRENT_DURATION="CHANGE_CURRENT_DURATION",
    RANDOM_TODO="RANDOM_TODO",
    UPDATE_TABLE="UPDATE_TABLE",
    UPDATE_MINUTES="UPDATE_MINUTES",
    START_TIMER="START_TIMER",
    NEXT_TODO="NEXT_TODO",
    FINISH_TODOLIST="FINISH_TODOLIST",
    RESET_TIMER="RESET_TIMER",
    UPDATE_TIMER ="UPDATE_TIMER"
   
}

export const enum Windows{
    SETTINGS_WINDOW="SETTINGS",
    PLAYLIST_WINDOW="PLAYLIST",
    SUGGESTION_WINDOW="SUGGESTION",
    HELP_WINDOW="HELP_PAGE",
    PLAY_SOUND="PLAY_SOUND"
}

